/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesIdRouteImport } from './routes/categories.$id'
import { Route as InstallmentsIndexRouteImport } from './routes/installments.index'
import { Route as InstallmentsIdRouteImport } from './routes/installments.$id'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageIdRouteImport } from './routes/manage.$id'
import { Route as ManageNewRouteImport } from './routes/manage.new'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ReceiptGroupRouteImport } from './routes/receipt.$group'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentsIndexRoute = InstallmentsIndexRouteImport.update({
  id: '/installments/',
  path: '/installments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentsIdRoute = InstallmentsIdRouteImport.update({
  id: '/installments/$id',
  path: '/installments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIdRoute = ManageIdRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageNewRoute = ManageNewRouteImport.update({
  id: '/manage/new',
  path: '/manage/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptGroupRoute = ReceiptGroupRouteImport.update({
  id: '/receipt/$group',
  path: '/receipt/$group',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/money': typeof MoneyRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/shops': typeof ShopsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/installments/$id': typeof InstallmentsIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/manage/new': typeof ManageNewRoute
  '/products/$id': typeof ProductsIdRoute
  '/receipt/$group': typeof ReceiptGroupRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/categories/': typeof CategoriesIndexRoute
  '/installments/': typeof InstallmentsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/money': typeof MoneyRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/shops': typeof ShopsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/installments/$id': typeof InstallmentsIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/manage/new': typeof ManageNewRoute
  '/products/$id': typeof ProductsIdRoute
  '/receipt/$group': typeof ReceiptGroupRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/categories': typeof CategoriesIndexRoute
  '/installments': typeof InstallmentsIndexRoute
  '/manage': typeof ManageIndexRoute
  '/products': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/money': typeof MoneyRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/shops': typeof ShopsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/installments/$id': typeof InstallmentsIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/manage/new': typeof ManageNewRoute
  '/products/$id': typeof ProductsIdRoute
  '/receipt/$group': typeof ReceiptGroupRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/categories/': typeof CategoriesIndexRoute
  '/installments/': typeof InstallmentsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/money'
    | '/people'
    | '/settings'
    | '/shops'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categories/$id'
    | '/installments/$id'
    | '/manage/$id'
    | '/manage/new'
    | '/products/$id'
    | '/receipt/$group'
    | '/verify/$code'
    | '/categories/'
    | '/installments/'
    | '/manage/'
    | '/products/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/money'
    | '/people'
    | '/settings'
    | '/shops'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categories/$id'
    | '/installments/$id'
    | '/manage/$id'
    | '/manage/new'
    | '/products/$id'
    | '/receipt/$group'
    | '/verify/$code'
    | '/categories'
    | '/installments'
    | '/manage'
    | '/products'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mcp'
    | '/money'
    | '/people'
    | '/settings'
    | '/shops'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categories/$id'
    | '/installments/$id'
    | '/manage/$id'
    | '/manage/new'
    | '/products/$id'
    | '/receipt/$group'
    | '/verify/$code'
    | '/categories/'
    | '/installments/'
    | '/manage/'
    | '/products/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  MoneyRoute: typeof MoneyRoute
  PeopleRoute: typeof PeopleRoute
  SettingsRoute: typeof SettingsRoute
  ShopsRoute: typeof ShopsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  InstallmentsIdRoute: typeof InstallmentsIdRoute
  ManageIdRoute: typeof ManageIdRoute
  ManageNewRoute: typeof ManageNewRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ReceiptGroupRoute: typeof ReceiptGroupRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  InstallmentsIndexRoute: typeof InstallmentsIndexRoute
  ManageIndexRoute: typeof ManageIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installments/': {
      id: '/installments/'
      path: '/installments'
      fullPath: '/installments/'
      preLoaderRoute: typeof InstallmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installments/$id': {
      id: '/installments/$id'
      path: '/installments/$id'
      fullPath: '/installments/$id'
      preLoaderRoute: typeof InstallmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$id': {
      id: '/manage/$id'
      path: '/manage/$id'
      fullPath: '/manage/$id'
      preLoaderRoute: typeof ManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/new': {
      id: '/manage/new'
      path: '/manage/new'
      fullPath: '/manage/new'
      preLoaderRoute: typeof ManageNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$group': {
      id: '/receipt/$group'
      path: '/receipt/$group'
      fullPath: '/receipt/$group'
      preLoaderRoute: typeof ReceiptGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  MoneyRoute: MoneyRoute,
  PeopleRoute: PeopleRoute,
  SettingsRoute: SettingsRoute,
  ShopsRoute: ShopsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  InstallmentsIdRoute: InstallmentsIdRoute,
  ManageIdRoute: ManageIdRoute,
  ManageNewRoute: ManageNewRoute,
  ProductsIdRoute: ProductsIdRoute,
  ReceiptGroupRoute: ReceiptGroupRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  InstallmentsIndexRoute: InstallmentsIndexRoute,
  ManageIndexRoute: ManageIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
